[package]
name = "mpcd"
version = "0.1.0"
authors = ["Antonín Dufka <xdufka1@fi.muni.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcsc = "2"
log = "0.4"
env_logger = "0.8"
