name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --no-default-features --verbose
    - name: Run tests
      run: cargo test --no-default-features --verbose
    - name: Run main
      run: cargo run --no-default-features --verbose -- --test
